### ISSUE TITLE
Предложение: воспроизвести звук гонга в конце обратного отсчёта

### ISSUE THREAD

**Issue by mrThomasTeller** [elushnikova/countdown#14]

**Comment by elushnikova** [comment]
Хм. Не нравится идея гонга, немного занимает идея с привязкой кастомного действия при завершении отсчёта — например, с одной из групп шутили про анимацию взрыва и кружащихся картинок по завершению счёта. 

Понимаю, что гонг может привлечь внимание к счётчику, который работает в фоне, но пока основная цель счётчика — постоянно визуализировать именно перерыв, без увода его в фон.

Вижу появление нового use case, но пока не готова к нему. Поэтому реализовывать в ближайшее время точно не буду — ощущается как что-то объёмное. Не уверена насчёт PR, но мне будет любопытно поглядеть на реализацию в форке, если таковой появится :D

**Comment by elushnikova** [comment]
Issue закрыла, но готова обсуждать в комментариях :D

**Comment by mrThomasTeller** [comment]
А может сделать в настройках опцию? Для меня гонг был бы удобен удобен

**Comment by elushnikova** [comment]
@mrThomasTeller, предлагаю реализовывать самостоятельно в форке — сама заниматься этим функционалом не буду 🙂
